### ISSUE TITLE
Scrolling beyond file contents

### ISSUE THREAD

**Issue by florianjacob** [jmacdonald/amp#11]
If you press the scroll down key repeatedly, you can scroll over the edge of the file as far as you want. It only works with the scroll key, not the cursor, though, which stops correctly at the end of the file.

The cursor is not moved when scrolling, though, in case this is not intentional this might be a related issue.

**Comment by jmacdonald** [comment]
Scrolling over the edge of a file is intentional :wink:. If it wasn't, when appending to the end of a file, the cursor would always be at the bottom of the screen (unless the entire file contents were smaller than the screen height). In some scenarios, working at the middle or top of the screen is more comfortable/ergonomic, even though you're not using the entire screen to display buffer contents.

That being said, scrolling beyond the entire buffer (where there is no content displayed on-screen) is definitely an issue. We can extend the scrollable region type's [scroll_down method](https://github.com/jmacdonald/amp/tree/master/src/view/scrollable_region.rs#L80-L82) to take an optional `limit` parameter, which we can use as a max value when updating `line_offset`. We can then also extend the view's [scroll_down delegation method](https://github.com/jmacdonald/amp/tree/master/src/view/mod.rs#L283-L285) to get the buffer line length and pass that as a limit.

If you're interested, feel free to run with this; happy to review/merge a PR if/when you do!

**Comment by florianjacob** [comment]
Thanks for the explanation of the intentions, I'll give it a try soon.

I think a sensible maximum for `line_offset` could be file length + terminal_height / 2, so that scrolling “snaps in“ when the last line reaches the center of the screen, because it doesn't make much sense to scroll down as far as to allow e.g. only the last line of a file at the top of the screen, which would be the ultimate maximum. What do you think?

**Comment by jmacdonald** [comment]
That sounds reasonable. :+1:

Tiny change, but max offset would end up being `file_line_length - terminal_height / 2`. We'll also want to used `checked_sub` to handle situations where `file_line_length` is less than half of `terminal_height`.
