### ISSUE TITLE
Termbox broken in Mac

### ISSUE THREAD

**Issue by hmohammadalt** [jmacdonald/amp#110]
error: failed to run custom build command for `termbox-sys v0.2.11`
process didn't exit successfully: `/var/folders/9n/hm_m4l7s6m56j8vr8lscty240000gn/T/cargo-installhWL7KA/release/build/termbox-sys-6bc601969fa0e77e/build-script-build` (exit code: 101)
--- stdout
running: "rm" "-rf" ".termbox"
running: "git" "clone" "https://github.com/nsf/termbox" ".termbox"
waf configure: setting CFLAGS to: `-m64 -fPIC`
running: "./waf" "configure" "--prefix=/"
Traceback (most recent call last):
  File "/Users/alt/.cargo/registry/src/github.com-1ecc6299db9ec823/termbox-sys-0.2.11/.termbox/.waf3-1.8.0-5c05be2d0e42d5c2c81403948a2d295b/waflib/Node.py", line 285, in ant_iter
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/alt/.cargo/registry/src/github.com-1ecc6299db9ec823/termbox-sys-0.2.11/.termbox/.waf3-1.8.0-5c05be2d0e42d5c2c81403948a2d295b/waflib/Scripting.py", line 98, in waf_entry_point
    run_commands()
  File "/Users/alt/.cargo/registry/src/github.com-1ecc6299db9ec823/termbox-sys-0.2.11/.termbox/.waf3-1.8.0-5c05be2d0e42d5c2c81403948a2d295b/waflib/Scripting.py", line 155, in run_commands
    parse_options()
  File "/Users/alt/.cargo/registry/src/github.com-1ecc6299db9ec823/termbox-sys-0.2.11/.termbox/.waf3-1.8.0-5c05be2d0e42d5c2c81403948a2d295b/waflib/Scripting.py", line 128, in parse_options
    Context.create_context('options').execute()
  File "/Users/alt/.cargo/registry/src/github.com-1ecc6299db9ec823/termbox-sys-0.2.11/.termbox/.waf3-1.8.0-5c05be2d0e42d5c2c81403948a2d295b/waflib/Options.py", line 138, in execute
    super(OptionsContext,self).execute()
  File "/Users/hmohammed.alt/.cargo/registry/src/github.com-1ecc6299db9ec823/termbox-sys-0.2.11/.termbox/.waf3-1.8.0-5c05be2d0e42d5c2c81403948a2d295b/waflib/Context.py", line 92, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/Users/alt/.cargo/registry/src/github.com-1ecc6299db9ec823/termbox-sys-0.2.11/.termbox/.waf3-1.8.0-5c05be2d0e42d5c2c81403948a2d295b/waflib/Context.py", line 133, in recurse
    user_function(self)
  File "/Users/alt/.cargo/registry/src/github.com-1ecc6299db9ec823/termbox-sys-0.2.11/.termbox/wscript", line 11, in options
    opt.load('compiler_c')
  File "/Users/alt/.cargo/registry/src/github.com-1ecc6299db9ec823/termbox-sys-0.2.11/.termbox/.waf3-1.8.0-5c05be2d0e42d5c2c81403948a2d295b/waflib/Context.py", line 89, in load
    fun(self)
  File "/Users/alt/.cargo/registry/src/github.com-1ecc6299db9ec823/termbox-sys-0.2.11/.termbox/.waf3-1.8.0-5c05be2d0e42d5c2c81403948a2d295b/waflib/Tools/compiler_c.py", line 36, in options
    opt.load_special_tools('c_*.py',ban=['c_dumbpreproc.py'])
  File "/Users/alt/.cargo/registry/src/github.com-1ecc6299db9ec823/termbox-sys-0.2.11/.termbox/.waf3-1.8.0-5c05be2d0e42d5c2c81403948a2d295b/waflib/Context.py", line 296, in load_special_tools
    lst=self.root.find_node(waf_dir).find_node('waflib/extras').ant_glob(var)
  File "/Users/alt/.cargo/registry/src/github.com-1ecc6299db9ec823/termbox-sys-0.2.11/.termbox/.waf3-1.8.0-5c05be2d0e42d5c2c81403948a2d295b/waflib/Node.py", line 334, in ant_glob
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
  File "/Users/alt/.cargo/registry/src/github.com-1ecc6299db9ec823/termbox-sys-0.2.11/.termbox/.waf3-1.8.0-5c05be2d0e42d5c2c81403948a2d295b/waflib/Node.py", line 334, in <listcomp>
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
RuntimeError: generator raised StopIteration

--- stderr
Cloning into '.termbox'...
thread 'main' panicked at 'assertion failed: cmd.stdout(Stdio::inherit()).stderr(Stdio::inherit()).status().unwrap().success()', /Users/alt/.cargo/registry/src/github.com-1ecc6299db9ec823/termbox-sys-0.2.11/build.rs:88:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: failed to compile `amp v0.5.1`, intermediate artifacts can be found at `/var/folders/9n/hm_m4l7s6m56j8vr8lscty240000gn/T/cargo-installhWL7KA`

Caused by:
  build failed

**Comment by jmacdonald** [comment]
Hi @hmohammadalt! This is [an issue](https://github.com/nsf/termbox/issues/117) with termbox, the library used to render Amp's UI. If your `python` executable points to v3.7, the build process for termbox fails. If I have a chance, I'll create a PR to help expedite that issue. I'm happy to provide instructions to work around the problem, but they involve pointing `python` to `python2` and that may not be what you want in general. :slightly_smiling_face:

**Comment by jmacdonald** [comment]
I should add: moving away from termbox is a goal for Amp. Having `python` as a build dependency is really sub-optimal, and there's no reason we can't rewrite termbox in Rust.

**Comment by hmohammadalt** [comment]
great, so what workaround I should do to make it work now, I have anaconda installed, if I activate python2.7 will it work ?

**Comment by matthias-t** [comment]
You don't need to rewrite termbox in Rust. There's already [`termion`](https://github.com/redox-os/termion)

**Comment by jmacdonald** [comment]
@hmohammadalt yep! When `termbox`'s build script calls `python`, that needs to resolve to python 2.x. As long as you settle that, it should build. :slightly_smiling_face: 

@matthias-t termion is considerably more low-level than termbox. Amp already has a termion-backed `Terminal` implementation that works, but termbox manages an in-memory buffer that sidesteps [flicker issues that occur in termion](https://gitlab.redox-os.org/redox-os/termion/issues/105). That's one of the major blockers to us adopting it wholesale (and trust me, I do want to adopt it :slightly_smiling_face:).

Implementing that same buffer for amp's `TermionTerminal` type is the next thing in my queue, so sit tight! You can track migration progress towards termion [here](https://github.com/jmacdonald/amp/compare/termion?expand=1), if you're interested.

**Comment by melMass** [comment]
You should remove `mac` from the title as this issue is the same across OSes

**Comment by matthias-t** [comment]
@jmacdonald if Termion is too low-level, can other projects benefit from a concise abstraction over it? Can you explain the flicker issues and the buffer in detail? I'd like to help!

**Comment by jmacdonald** [comment]
Hi @matthias-t! I'm sure other projects could benefit from an abstraction.

The flickering happens because of the `termion::clear::All` escape sequence. It's not Termion's fault; writing content to the screen, clearing it, and then writing content again _should_ cause a flicker, since there's an interstitial state where the content is blank.

The trick to avoiding flicker is to overwrite the old content, rather than clearing it. There are a couple of gotchas to this, though:

1. You need to ensure the entire screen is drawn, otherwise you'll leave old content in areas that haven't been drawn.
2. You need to ensure that any position is only drawn _once_. You might wonder why you'd draw something twice, so I'll give an example: Amp's open mode. When in this mode, we first render the current buffer, and then we draw an area at the top of the screen to display file paths and a search input field. The area at the top of the screen overlaps with the buffer. If you ignore that fact, you'll see flickering on the screen in that area as the buffer content is drawn and then overwritten with the open mode UI content. Using Termion directly, _we cannot have overlapping render regions_, or we introduce flickering. I created a branch to update this process to avoid overlapping, and it was a mess. Bleeding those sorts of flickering concerns up into the presenter, buffer renderer, etc. was a poor fit.

Termbox solves all of this with a screen buffer. Everything is written to the buffer, and only rendered _once_ to the screen, at the very end. The clear flickering is avoided because it simply updates all of the buffer cells with blank content. Overlapping regions are also solved because multiple writes to the buffer aren't drawn to the screen; the only time the screen is rendered is after a call to `present`, so the terminal emulator sees a single, atomic screen update that never uses the `clear` escape sequence.

There is one shortcoming to termbox: it represents each cell as a single, 32-bit unsigned integer. That works fine for single-codepoint characters (a `char` in Rust), but it'll never support grapheme clusters. The only way to do that is to have each of the cells be a string. Allocating a string for each of the cells would provide poor performance, but we can avoid that by using string slices (which are borrowed, and therefore not allocated). That's the design I'm working on at the moment, but it requires a non-trivial rework of Amp's presenter pattern (right now the screen buffer is owned by the `Terminal` type, but it needs to be ephemeral, as its content is borrowed). If you wanted to build a crate that used this design, you'd need to build it in such a way that the buffer is discarded after being rendered, so that its borrowed content is relinquished.

My plan is to implement this in Amp directly, and then investigate extracting it into a separate crate, although admittedly the latter is a much lower priority at the moment. If you're interested, you can follow along in `termion-buffer`, or feel free to experiment with a new crate that builds this abstraction on top of Termion! I'm happy to share whatever findings I come across as I build this here. :slightly_smiling_face:

**Comment by matthias-t** [comment]
Thanks!

> Everything is written to the buffer, and only rendered once to the screen, at the very end.

Is that what [`rustty`](https://github.com/cpjreynolds/rustty) does? (Its [`Cell`](https://docs.rs/rustty/0.1.12/src/rustty/core/cellbuffer.rs.html#166-171)s hold a `char` though, and there's an issue open about long unicode characters.)

**Comment by jmacdonald** [comment]
Looks like it! `rustty` looks an awful lot like termbox, which is where this abstraction first appeared.

**Comment by melMass** [comment]
Is there a workaround for this on win32 ? 
I want to use AMP on my chrome tablet...

**Comment by jmacdonald** [comment]
@melMass Win32 isn't a supported platform at the moment, but assuming you're running into the same issue, you'll need to find a way to have `python` resolve to something `< 3.7.0`.

**Comment by cecton** [comment]
On Linux you can do:
```
mkdir /tmp/bin
ln -s /usr/bin/python2 /tmp/bin/python
PATH=/tmp/bin:$PATH cargo install amp
```

To override the default Python temporarily....

Looking forward to see this dependency out.

**Comment by jmacdonald** [comment]
Looks like Python 3.7 support has been [added upstream](https://github.com/nsf/termbox/pull/121). Can someone give their build another try to see if it resolves the issue? Will likely need to run `cargo clean` before building to ensure the latest version is fetched.

**Comment by jmacdonald** [comment]
@cecton the upstream fix landed 10 hours ago. :smile:

**Comment by cecton** [comment]
-_- very funny. I did the cargo clean and rebuilt without the PATH and it worked so I guess it works with Python 3 now unless there was some sort of cache somewhere.

So we can close this issue?

**Comment by cecton** [comment]
I still have one question (just pure curiosity): I saw people complaining that win32 platform is not supported. But since Microsoft added support for WSL, they also added support for terminal compatibility with *nix-like terminals for cmd.exe right? How come it doesn't work out of the box now?

**Comment by matthias-t** [comment]
I didn't setup any workaround in the fist place, and amp builds just fine now on arch linux. I agree that this issue can be closed. However, could we create an issue to track migration away from termbox?

**Comment by matthias-t** [comment]
> right now the screen buffer is owned by the `Terminal` type, but it needs to be ephemeral, as its content is borrowed

@jmacdonald Is it possible to own the buffer and at the same time hold slices to it that segment it into cells?

**Comment by matthias-t** [comment]
Also, can you slice a `Rope`?

**Comment by jmacdonald** [comment]
> Oh I get it: your model owns the data and your `Terminal` renders from views into it! right?

@matthias-t yep!

> But what if your model doesn't own a `String`? What if your model stores data in non-contiguous locations in memory, like a `Rope`?

@matthias-t as long as it can yield string slices, it can be presented. Amp uses a gap buffer under the hood; although it does allocate a string with a contiguous data block, there's no reason it couldn't yield two slices, both of which could be rendered via the `Terminal` type.

**Comment by jmacdonald** [comment]
I'm going to close this issue, as termbox is no longer broken. If you're looking forward to a termbox-free version of Amp, just keep your eyes peeled for `v0.6.0`!
