### ISSUE TITLE
Unable to load terraform syntax file?

### ISSUE THREAD

**Issue by webframp** [jmacdonald/amp#122]
Hey, great project here! The speed, jump commands and fuzzy finder are excellent.

I tried using this syntax according to the wiki instructions but must be missing something:
* https://github.com/alexlouden/Terraform.tmLanguage/blob/3c8a32645695573e1c3204db27a4f16b58fe362f/Terraform.sublime-syntax

<img width="487" alt="image" src="https://user-images.githubusercontent.com/774378/48973903-89685e80-f018-11e8-842d-83434b8875ad.png">

I am using this file also with https://github.com/sharkdp/bat to add syntax support for tf files, which works, but I'm not sure what I'm missing or what's different for amp. It also uses syntect as described here: https://github.com/sharkdp/bat#adding-new-syntaxes--language-definitions 

any ideas?

**Comment by jmacdonald** [comment]
Hi @webframp! Thanks, I'm glad you're digging amp so far. :smile: 

Hmm, I'm getting the same issue locally. Let me debug this and see if I can find the root cause; I'll post an update shortly.

**Comment by jmacdonald** [comment]
I was able to isolate this to files opened as an argument when first running amp; it didn't occur when opening files using the fuzzy finder.

Syntax definitions are associated when a buffer is opened, and unfortunately, I was loading user-configured definitions _after_ opening files specified as arguments. This has been fixed in master; can you build from source and let me know if this settles it for you? If not, feel free to reopen this issue. :slightly_smiling_face:

**Comment by webframp** [comment]
Tested current master, looks like 4a05180a5ec5ae2d8bd17d8f09f2a3648701e700 fixed it. Thanks @jmacdonald !

**Comment by jmacdonald** [comment]
Glad to hear it, @webframp; thanks for filing this!
