### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by flosse** [jmacdonald/amp#27]
It would be cool to install amp with `cargo install amp` :)

**Comment by jmacdonald** [comment]
Unfortunately, [that name is taken](https://crates.io/crates/amp). There's also this stumbling block at the moment:

https://github.com/rust-lang/cargo/issues/2263

Sounds like binary builds aren't deterministic when fetched through crates.io, because crates don't include `Cargo.lock` when being packaged. For the time being, I can at least update the installation instructions to refer to Cargo's `--git` option. 🙂

**Comment by jmacdonald** [comment]
https://amp.rs/docs/installation/ have been updated to provide a `--git` suggestion, for the time being.

**Comment by flosse** [comment]
perfect!
