### ISSUE TITLE
Files always have an empty line at the end: no implicit terminating newline?

### ISSUE THREAD

**Issue by EdSchouten** [jmacdonald/amp#31]
When editing existing source files created by other editors such as vim, I see that files in amp always have an empty line at the end. This is likely because amp doesn't terminate the last line of a file with a newline.

Though there are some editors out there that follow the same behaviour as amp, it's not the convention used by most editors for UNIX-like systems. The newline is there to make printing them to a terminal work correctly (without messing up the next shell prompt), concatenation of multiple files using `cat`, etc.

**Comment by jmacdonald** [comment]
@EdSchouten Amp actually follows that UNIX idiom! I think you might be getting confused by how it's rendered, though. The `BufferRenderer` will actually draw a separate line (with a line number) at the bottom of the buffer. In short, every time a buffer is saved, Amp does two things:

1. removes trailing whitespace
2. ensures there's a trailing newline

Please check the saved contents of the buffer using `cat`. If you're actually seeing incorrect output, then that's a legitimate bug. Assuming not, I think the solution here is to update the docs with a note indicating that Amp does this automatically (and it's not configurable, since I can't imagine a scenario where we _wouldn't_ want this behaviour).

**Comment by EdSchouten** [comment]
Hey! You're correct! It always adds a trailing newline. Thanks for clarifying!
