### ISSUE TITLE
Inconsistent key to delete line

### ISSUE THREAD

**Issue by lord-re** [jmacdonald/amp#71]
While il *normal mode* you can press **;** to delete the current line if you are in *visual mode* with some lines selected, you must press **d** to delete lines.

**Comment by jmacdonald** [comment]
I've added `;` as a delete key binding in _select line_ mode. I haven't added it to select mode, only because that's somewhat ambiguous behaviour. `;` is reserved for deleting lines, which makes sense in normal mode (the current line) and select line mode (the selected lines), but isn't quite as clear in visual mode. If the selection is on a single line, it's somewhat obvious (delete the current line), but then why is the user in select mode? And if the selection spans more than a single line, they should be using select line mode.
